name: Teams EXE
 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
 
    - name: Install dependencies
      run: |
        pip install pyinstaller pyautogui
 
    - name: Build exe
      run: |
        pyinstaller --onefile --noconsole Teams.py
 
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: Teams-exe
        path: dist/Teams.exe
